### ISSUE TITLE
jsonapi-serializer freezes the browser when nested include is used

### ISSUE THREAD

**Issue by thehappycoder** [SeyZ/jsonapi-serializer#76] opened 2016-04-04 04:48 UTC
jsonapi-serializer 3.0.1

The resources I include: calendar_event, space,host.profile

```
new Deserializer({keyForAttribute: 'snake_case'}).deserialize(input, (err, resource) => {
          console.log(resource);
          onSuccess(response, resource);
        });
```

Here is the input:

```
{
  "data": {
    "id": "524",
    "type": "events",
    "attributes": {
      "name": "Omnis labore laboriosam magni qui.",
      "status": "pending",
      "cost_cents": 7577,
      "description": "perferendis molestiae voluptatem",
      "is_public": true,
      "bartender": false
    },
    "relationships": {
      "calendar_event": {
        "data": {
          "id": "424",
          "type": "calendar_events"
        }
      },
      "host": {
        "data": {
          "id": "1",
          "type": "users"
        }
      },
      "space": {
        "data": {
          "id": "1",
          "type": "spaces"
        }
      }
    }
  },
  "included": [
    {
      "id": "424",
      "type": "calendar_events",
      "attributes": {
        "title": "Booking",
        "availability": "busy",
        "starts_at": "2016-03-25T06:30:00.000Z",
        "ends_at": "2016-03-25T13:30:00.000Z",
        "ical_schedule": null
      },
      "relationships": {
        "resource": {
          "data": {
            "id": "524",
            "type": "events"
          }
        }
      }
    },
    {
      "id": "1",
      "type": "users",
      "attributes": {
        "email": "my@email.com",
        "roles": []
      },
      "relationships": {
        "profile": {
          "data": {
            "id": "1",
            "type": "profiles"
          }
        }
      }
    },
    {
      "id": "1",
      "type": "profiles",
      "attributes": {
        "first_name": "Anton",
        "last_name": "Anton",
        "birthday": "1905-12-10",
        "avatar_original_url": "aha!",
        "avatar_thumb_url": "aha!",
        "bio": null,
        "phone": "aha!",
        "address_line_1": "aha!",
        "address_line_2": null,
        "city": "aha!",
        "state": "aha!",
        "postcode": "aha!",
        "country_code": null
      },
      "relationships": {
        "user": {
          "data": {
            "id": "1",
            "type": "users"
          }
        }
      }
    },
    {
      "id": "1",
      "type": "spaces",
      "attributes": {
        "name": "Space #1",
        "from_people": 1,
        "to_people": 10,
        "picture_original_url": "aha!",
        "picture_thumb_url": "aha!",
        "picture_thumb_2x_url": "aha!",
        "credits_per_slot": 10
      }
    }
  ]
}
```

**Comment by pzmudzinski** [comment] 2016-10-31 14:40
any news on that?

**Comment by mikeallisonJS** [comment] 2017-01-27 18:25
looks like a circular reference to events causing infinite recursion, I'm having the same issue.

**Comment by greyvugrin** [comment] 2017-02-24 23:05
@SeyZ hi would you have any insight on what is happening here? Thanks! Having the same issue

**Comment by itsravenous** [comment] 2017-03-29 13:51
Having the same issue - assuming it's infinite recursion.

**Comment by zweck** [comment] 2017-03-30 08:37
Hey, I've also ran into this issue this week.

**Comment by SeyZ** [comment] 2017-03-31 15:54
Hey @zweck @itsravenous @greyvugrin @mikeallisonJS @pzmudzinski and @thehappycoder 
I'm very sorry for the delay!

I've tried to reproduce this issue here:
https://gist.github.com/SeyZ/8df5dd6a52f716548d594f520384ad6a

And unfortunately, I don't have any infinite loop

![screen shot 2017-03-31 at 17 53 22](https://cloud.githubusercontent.com/assets/519129/24558302/f6c28b54-163a-11e7-9947-2340efab577d.png)

Do you guys use the latest version? (3.4.2)

**Comment by SeyZ** [comment] 2017-03-31 16:01
Sorry for delay guys, I've reproduced this issue and will fix it soon!

**Comment by SeyZ** [comment] 2017-03-31 16:18
@zweck @itsravenous @greyvugrin @mikeallisonJS @pzmudzinski @thehappycoder it's now fixed on the new version :) Thank you and sorry for the delay one more time!

**Closed** 2017-03-31 16:18 UTC

**Comment by greyvugrin** [comment] 2017-03-31 16:50
Thanks! I'll update soon

**Comment by itsravenous** [comment] 2017-04-03 07:17
Thanks @SeyZ!

**Comment by zweck** [comment] 2017-04-03 07:22
Hi @SeyZ I've dropped v3.4.3 into my project and it's all good :) thanks 👍
