### ISSUE TITLE
Using JSON API Serializer to create more complicated JSON 

### ISSUE THREAD

**Issue by two7sclash** [SeyZ/jsonapi-serializer#152] opened 2017-09-01 01:41 UTC
The examples here don't go nearly far enough in explaining how to produce a more complicated structure...

If I want to end up with something like:

```
{
  "data": {
    "type": "mobile_screens",
    "id": "1",
    "attributes": {
      "title": "Watch"
    },
    "relationships": {
      "mobile_screen_components": {
        "data": [
          {
            "id": "1_1",
            "type": "mobile_screen_components"
          },
          {
            "id": "1_2",
            "type": "mobile_screen_components"
          },
          ...
        ]
      }
    }
  },
  "included": [
    {
      "id": "1_1",
      "type": "mobile_screen_components",
      "attributes": {
        "title": "Featured Playlist",
        "display_type": "shelf"
      },
      "relationships": {
        "playlist": {
          "data": {
            "id": "938973798001",
            "type": "playlists"
          }
        }
      }
    },
    {
      "id": "938973798001",
      "type": "playlists",
      "relationships": {
        "videos": {
          "data": [
            {
              "id": "5536725488001",
              "type": "videos"
            },
            {
              "id": "5535943875001",
              "type": "videos"
            }
          ]
        }
      }
    },
    {
      "id": "5536725488001",
      "type": "videos",
      "attributes": {
        "duration": 78321,
        "live_stream": false,
        "thumbnail": {
          "width": 1280,
          "url":
            "http://xxx.jpg?pubId=694940094001",
          "height": 720
        },
        "last_published_date": "2017-08-09T18:26:04.899Z",
        "streams": [
          {
            "url":
              "http://xxx.m3u8",
            "mime_type": "MP4"
          }
        ],
        "last_modified_date": "2017-08-09T18:26:27.621Z",
        "description": "xxx",
        "fn__media_tags": [
          "weather",
          "personality"
        ],
        "created_date": "2017-08-09T18:23:16.830Z",
        "title": "NOAA predicts most active hurricane season since 2010",
        "fn__tve_authentication_required": false
      }
    },
    ...,
    {
      "id": "1_2",
      "type": "mobile_screen_components",
      "attributes": {
        "title": "Live Streams",
        "display_type": "shelf"
      },
      "relationships": {
        "videos": {
          "data": [
            {
              "id": "1241186546001",
              "type": "videos"
            },
            {
              "id": "1251429410001",
              "type": "videos"
            }
          ]
        }
      }
    },
    {
      "id": "1241186546001",
      "type": "videos",
      "attributes": {
        "thumbnail": {
          "width": 1280,
          "url":
            "xxx.jpg?pubId=694940094001",
          "height": 720
        },
        "streams": [
          {
            "url":
              "http://xxx.m3u8",
            "mime_type": "FLV"
          }
        ],
        "last_modified_date": "2017-05-08T16:11:22.585Z",
        "description": "xxx",
        "fn__media_tags": ["live_stream|fnc", "live_stream"],
        "title": "xxx",
        "fn__tve_authentication_required": true,
        "duration": -1,
        "live_stream": true,
        "last_published_date": "2012-01-02T19:59:57.030Z",
        "created_date": "2011-10-26T14:27:41.808Z"
      }
    },
    ...,

    {
  ]
}
```
what is the most simple data structure and serializer I can set up?

I get stumped after something like:

```
const mobile_screen_components = responses.map((currentValue, index) => {
      id[`id_${index}`];
    });
    const dataSet = {
      id: 1,
      title: 'Watch',
      mobile_screen_components,
    };
    const ScreenSerializer = new JSONAPISerializer('mobile_screens', {
      attributes: ['title', 'mobile_screen_components'],
      mobile_screen_components: {
        ref: 'id',
      },
    });
```
Which only gives me:

```
{
  "data": {
    "type": "mobile_screens",
    "id": "1",
    "attributes": { "title": "Watch" },
    "relationships": {
      "mobile-screen-components": {
        "data": [
          { "type": "mobile_screen_components", "id": "1_0" },
          { "type": "mobile_screen_components", "id": "1_1" },
          { "type": "mobile_screen_components", "id": "1_2" },
          { "type": "mobile_screen_components", "id": "1_3" },
          { "type": "mobile_screen_components", "id": "1_4" },
          { "type": "mobile_screen_components", "id": "1_5" }
        ]
      }
    }
  }
}
```
I have no idea how to get the "included" sibling to "data." etc.

**Comment by SeyZ** [comment] 2017-09-09 08:17
hey @two7sclash - you can find complex examples in the `test/` directory. If you need more help, can you give me the raw json input ? Then I'll show you how to serialize it to have your expected result.

I close this issue because it's not a bug or a feature asked. I'll answer here when I have the raw json input.

**Closed by SeyZ** 2017-09-09 08:17 UTC
